### ISSUE TITLE
"Cannot find module 'co"

### ISSUE THREAD

**Issue by WesSec** [ducdigital/ticketswap-watch#1]
Hi,

I get the following error as i run your script

```
Error: Cannot find module 'co'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\nodejs\app.js:3:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

i'm using nodejs 6.10.3 on Windows 10
Is there anything i need preinstalled for the script?

**Comment by WesSec** [comment]
Nevermind, easy install the modules using npm install
